### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "alan@cinesfera.com",
    "password": "123456"
}

### Signup
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "username": "alan",
    "email": "prueba@alan.com",
    "password": "123456",
    "biography": "Alan"
}

### Logout
POST http://localhost:3000/api/auth/logout
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiQWxhbl9DaW5lc2ZlcmEiLCJlbWFpbCI6ImFsYW5AY2luZXNmZXJhLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3MjQ0MTM2NCwiZXhwIjoxNzcyNDQ0OTY0fQ.1do1PRHT0BmPstCXGbm1xMhvDtP3yNPicUNDUH-hQ3E

