### GET /api/home/trending
GET http://localhost:3000/api/home/trending
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiQWxhbnNpdG8iLCJlbWFpbCI6ImFsYW5AY2luZXNmZXJhLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3MzMwOTI5NCwiZXhwIjoxNzczMzEyODk0fQ.CcVsqrDD8keEzGVNwWbNRD3Lq9n60bUjAOE12wpRQAs

### GET /api/home/popular
GET http://localhost:3000/api/home/popular/movie
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiQWxhbnNpdG8iLCJlbWFpbCI6ImFsYW5AY2luZXNmZXJhLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3MzMwOTI5NCwiZXhwIjoxNzczMzEyODk0fQ.CcVsqrDD8keEzGVNwWbNRD3Lq9n60bUjAOE12wpRQAs

### GET /api/home/top_rated
GET http://localhost:3000/api/home/top_rated/tv
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiQWxhbnNpdG8iLCJlbWFpbCI6ImFsYW5AY2luZXNmZXJhLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3MzMwOTI5NCwiZXhwIjoxNzczMzEyODk0fQ.CcVsqrDD8keEzGVNwWbNRD3Lq9n60bUjAOE12wpRQAs

### GET /api/home/by_genre
GET http://localhost:3000/api/home/by_genre/movie/35
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiQWxhbnNpdG8iLCJlbWFpbCI6ImFsYW5AY2luZXNmZXJhLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3MzMwOTI5NCwiZXhwIjoxNzczMzEyODk0fQ.CcVsqrDD8keEzGVNwWbNRD3Lq9n60bUjAOE12wpRQAs

### GET /api/home/providers
GET http://localhost:3000/api/home/providers/movie/1011985
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiQWxhbnNpdG8iLCJlbWFpbCI6ImFsYW5AY2luZXNmZXJhLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3MzMxMzIxMCwiZXhwIjoxNzczMzE2ODEwfQ.7XzDJ40nevya75RLaCRG2ddm9NDSvQE7I6OjWi80y4w